export const questions: string[] = [
  "Qual foi o momento mais feliz da sua vida?",
  "Se você pudesse mudar uma coisa no mundo, o que seria?",
  "Qual é o seu maior sonho?",
  "O que te faz rir de verdade?",
  "Qual memória nossa você mais guarda no coração?",
  "Se pudéssemos viajar para qualquer lugar agora, onde seria?",
  "O que você mais admira em mim?",
  "Qual foi o momento em que você soube que me amava?",
  "O que você gostaria de fazer mais comigo?",
  "Qual é o seu maior medo?",
  "Como você imagina nossas vidas daqui a 10 anos?",
  "Qual foi a coisa mais corajosa que você já fez?",
  "O que te faz sentir amado(a)?",
  "Se você pudesse reviver um dia da sua vida, qual seria?",
  "Qual tradição você gostaria de criar como casal?",
  "O que te deixa mais orgulhoso(a) de si mesmo(a)?",
  "Qual foi o melhor conselho que você já recebeu?",
  "O que você acha que nos faz funcionar como casal?",
  "Qual é a sua linguagem do amor preferida?",
  "Se não tivesse limitações, que carreira você seguiria?",
  "Qual característica minha você gostaria de ter?",
  "O que você gostaria de aprender a fazer?",
  "Qual foi nosso encontro mais memorável?",
  "O que te faz sentir seguro(a) no nosso relacionamento?",
  "Qual aventura você gostaria de viver comigo?",
  "O que te deixa mais feliz no dia a dia?",
  "Como você lida com o estresse?",
  "Qual foi a maior lição que a vida te ensinou?",
  "O que você mais valoriza em um relacionamento?",
  "Qual hábito meu você mais gosta?",
  "Se pudesse jantar com qualquer pessoa, quem seria?",
  "O que te faz sentir realizado(a)?",
  "Qual é o seu lugar favorito no mundo?",
  "O que você gostaria que eu soubesse sobre você?",
  "Como você imagina nossa casa dos sonhos?",
  "Qual música te lembra de mim?",
  "O que você faria se ganhasse na loteria?",
  "Qual foi o momento mais difícil que já superamos juntos?",
  "O que te dá esperança?",
  "Qual é a sua melhor lembrança da infância?",
  "Como você gostaria de ser lembrado(a)?",
  "O que te motiva a acordar todos os dias?",
  "Qual foi a primeira coisa que você notou em mim?",
  "O que você mais gosta de fazer quando estamos juntos?",
  "Qual é o seu maior arrependimento?",
  "Como você se sente quando estamos separados?",
  "O que você acha que eu deveria saber, mas nunca perguntei?",
  "Qual foi a melhor surpresa que você já recebeu?",
  "O que te faz se sentir vivo(a)?",
  "Como você descreveria nosso relacionamento em três palavras?",
  "Qual é o seu filme favorito e por quê?",
  "O que você mais gosta em si mesmo(a)?",
  "Qual pequeno gesto meu te faz feliz?",
  "O que você acha que torna um relacionamento forte?",
  "Qual é a sua forma favorita de demonstrar amor?",
  "Se pudesse ter qualquer superpoder, qual seria?",
  "O que você gostaria de fazer mais pelo nosso relacionamento?",
  "Qual foi o melhor presente que você já recebeu?",
  "Como você se sente sobre nosso futuro juntos?",
  "O que te faz chorar de emoção?",
  "Qual é a sua comida favorita que eu faço?",
  "O que você mais valoriza no tempo que passamos juntos?",
  "Qual sonho de infância você ainda quer realizar?",
  "Como você gostaria de comemorar nosso próximo aniversário?",
  "O que você admira nos seus pais?",
  "Qual característica você gostaria de passar para nossos filhos?",
  "O que te faz sentir gratidão?",
  "Qual foi o momento em que você mais se orgulhou de mim?",
  "O que você gostaria de mudar na sua rotina?",
  "Como você imagina nosso envelhecer juntos?",
  "Qual é a sua estação do ano favorita e por quê?",
  "O que te faz perder a noção do tempo?",
  "Qual foi a melhor decisão que você já tomou?",
  "O que você gostaria de experimentar pelo menos uma vez na vida?",
  "Como você se descreveria em uma palavra?",
  "Qual é a sua forma favorita de relaxar?",
  "O que te faz confiar em alguém?",
  "Qual objetivo você quer alcançar esse ano?",
  "O que você mais ama sobre nossa história?",
  "Qual foi o momento mais engraçado que já vivemos juntos?",
  "O que te inspira?",
  "Como você gostaria de ser apoiado(a) por mim?",
  "Qual livro mudou sua vida?",
  "O que você acha que eu não sei sobre você?",
  "Qual tradição de família você quer manter?",
  "O que te faz sentir em paz?",
  "Como você lida com as diferenças entre nós?",
  "Qual foi o melhor dia da sua vida?",
  "O que você espera do nosso relacionamento?",
  "Qual lugar você gostaria de me levar?",
  "O que te faz sentir especial?",
  "Como você mostra que se importa?",
  "Qual foi a coisa mais romântica que já fizemos?",
  "O que você acha que falta no nosso relacionamento?",
  "Qual momento nosso você reviveria?",
  "O que te mantém acordado(a) à noite?",
  "Como você imagina um domingo perfeito comigo?",
  "Qual é o seu maior objetivo de vida?",
  "O que você mais aprecia em nossa conexão?",
  "Qual desafio você quer superar comigo?",
  "O que faz você se sentir verdadeiramente amado(a)?",
  "Qual memória você gostaria de criar comigo?",
  "O que você acha que nos diferencia de outros casais?",
  "Qual versão de nós dois você mais gosta?",
  "O que te faz querer ser uma pessoa melhor?",
  "Como você se sente quando olha nos meus olhos?",
  "Qual promessa você gostaria de fazer para nós?",
  "O que você mais espera do amanhã?",
  "Qual momento você gostaria de congelar no tempo?",
  "O que nosso amor significa para você?",
];

export function getQuestionForDate(date: Date): string {
  const dateString = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
  let hash = 0;
  for (let i = 0; i < dateString.length; i++) {
    const char = dateString.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  const index = Math.abs(hash) % questions.length;
  return questions[index];
}

export function formatDateKey(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}
